### ISSUE TITLE
Backend feels limiting

### ISSUE THREAD

**Issue by PaluMacil** [desol/lhj#1]
The server part might be more powerful if any code were to be added.

**Comment by desol** [comment]
This was a stylistic choice for the project. The team sees your concern, but we do not currently see a true benefit to adding code to the server.

**Comment by PaluMacil** [comment]
Are you going to tag this as "wontfix" or add it to a 2.0 milestone?

**Comment by PaluMacil** [comment]
The progress on this is promising, but everything is still broken. You should get an alpha release date announcement posted.
